name: "Regression Check"

on:

  # no timezone support so cron runs in UTC time for now
  # schedule:
  #   - cron: "8 15 * * *"

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

  workflow_call:

  push:

  pull_request:

jobs:

  android-coin-flipper:
    name: "Android Coin Flipper"
    uses: michaeltchuang/.github/.github/workflows/android-app-tests.yml@main
    with:
        app_workspace: "android"
